### PR TITLE
prevent infinite loop

### PR DESCRIPTION
**Pull request by Franzsardoma**
I experienced this issue while performing subtract, when I add this block it went fine, Thank you for this project

### CODE REVIEW

**Comment by wtaisto** [comment]
I've run into a handfull of mesh pairs that trigger this runaway condition as well, blowing up a simple 12 face mesh into millions of triangles before running out of memory.  I'm curious why this error check was not included from the java port?  Is there perhaps a better way to detect when a given pair of meshes will cause this?

I love this lib by the way!

**Comment by arakis** [comment]
thx for hinting to that problem! If there's a better fix, just make a new PR.

**Comment by wtaisto** [comment]
I definitely don't fully understand the guts of these algorithms, but it seems like the runaway condition occurs for me when I have a pair of solids A and B, I try to subtract B from A, and if A and B are essentially outside of each other but ever so slightly overlapping on a face, then it goes into face-loop-explosion.  Might it have to do with floating point quantization error, where coplanar opposing faces kind of dither along their overlap, oscillating between being seen as "inside" and "outside" each other?  I've just run into this when running various complicated meshes, I'll try to write up a test method that generates the simplest meshes possible which still trigger the runaway.

**Comment by arakis** [comment]
This would be greate. In general, we should add some unit tests within that repo :-/

**Pull request merged**
